### ISSUE TITLE
The missing comma highlight is on the wrong line

### ISSUE THREAD

**Issue by jperdereau** [victorporof/Sublime-JSHint#112] opened 2015-06-11 05:45 UTC
SL version: 2.0.2 build 2221
OS: OS X Yosemite 10.10.3 (14D136)

![screen shot 0027-06-11 at 14 39 11](https://cloud.githubusercontent.com/assets/1787382/8100529/1106d164-1048-11e5-9844-3ea1f9adb034.png)
The highlight should be on line 60

plugin settings:
```
{
  // Simply using `node` without specifying a path sometimes doesn't work :(
  // https://github.com/victorporof/Sublime-JSHint#oh-noez-command-not-found
  // http://nodejs.org/#download
  "node_path": {
    "windows": "C:/Program Files/nodejs/node.exe",
    "linux": "/usr/bin/nodejs",
    "osx": "/usr/local/bin/node"
  },

  // Automatically lint on edit (Sublime Text 3 only).
  "lint_on_edit": false,

  // Configurable duration before re-linting.
  "lint_on_edit_timeout": 1,

  // Automatically lint when a file is loaded.
  "lint_on_load": true,

  // Automatically lint when a file is saved.
  "lint_on_save": true,

  // Highlight problematic regions when selected.
  "highlight_selected_regions": true,

  // Log the settings passed to JSHint from `.jshintrc`.
  "print_diagnostics": true
}
```

**Comment by victorporof** [comment] 2016-01-18 17:27
Looks like a dupe of https://github.com/victorporof/Sublime-JSHint/issues/34

**Closed by victorporof** 2016-01-18 17:27 UTC
